# Generated by Django 5.0.4 on 2024-06-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='trext',
        ),
    ]
