# Generated by Django 5.0.4 on 2024-06-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_comments_email_remove_comments_trext'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('passion', models.TextField()),
                ('work', models.TextField()),
            ],
        ),
    ]
